name: kpfpipe
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.14.3
  - GitPython>=3.1.0
  - matplotlib==3.10.8
  - numpy==2.4.2
  - pandas==3.0.0
  - scipy==1.17.0
  - tqdm==4.67.3
  - pip
  - pip:
      - astropy==7.2.0
      - astroquery==0.4.11
      - barycorrpy==0.4.4
      - rv-data-standard @ git+https://github.com/EPRV-RCN/RVData.git@develop
      # --- development tools --- #
      - black==26.1.0
      - flake8==7.3.0
      - ipykernel==7.2.0
      - isort==7.0.0
      - jupyterlab=4.5.4
      - line_profiler
      - mypy==1.19.1
      - notebook=7.5.3
      - pytest==9.0.2
