name: kpfpipe
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.14.3
  - GitPython>=3.1.0
  - h5py==3.15.1
  - matplotlib==3.10.8
  - numpy==2.4.2
  - pandas==3.0.0
  - pillow==12.1.1
  - scipy==1.17.0
  - tqdm==4.67.3
  - pip
  - pip:
      - astropy==7.2.0
      - astroquery==0.4.11
      - barycorrpy==0.4.4
      - rv-data-standard==0.4.0
      # --- development tools --- #
      - ipykernel==7.2.0
      - jupyterlab==4.5.4
      - line_profiler
      - mypy==1.19.1
      - notebook==7.5.3
      - pre-commit==4.6.0
      - pytest==9.0.2
      - pytest-cov==7.0.0
      - pytest-xdist==3.6.1
      - ruff==0.15.17
