# WMKO observatory coordinates

geosys = "GRS80"         # Geodetic reference system of the coordinates below
longitude = -155.474719  # (degrees)
latitude = 19.826        # (degrees)
altitude = 4145.0        # (meters)
