# WMKO observatory coordinates

geosys = "WGS84"         # Geodetic reference system of the coordinates below
longitude = -155.474718  # East-positive (degrees)
latitude = 19.825946     # (degrees)
altitude = 4159.58       # Height above the ellipsoid (meters)
