[DATA_DIRS]
KPF_DATA_INPUT = "/data/kpf/"
KPF_DATA_OUTPUT = "/data/kpf-next/"

[KPFPIPE]
chips = ["GREEN", "RED"]
fibers = ["SKY", "SCI1", "SCI2", "SCI3", "CAL"]

[BIAS]
dummy = None

[DARK]
dummy = None

[FLAT]
dummy = None