[DATA_DIRS]
KPF_DATA_INPUT = "/data/kpf/"
KPF_DATA_OUTPUT = "/data/kpf-next/"

[KPFPIPE]
chips = ["GREEN", "RED"]
fibers = ["SKY", "SCI1", "SCI2", "SCI3", "CAL"]

[BIAS]
stack_sigma = 5.0

[DARK]
stack_sigma = 5.0

[FLAT]
stack_sigma = 5.0

[WLS]
lineprofile = "gaussian"
polyorder_x = 6
polyorder_m = 6
polyorder_f = 2

[MODULE_IMAGE_ASSEMBLY]
overscan_method = "rowmedian"
readnoise_sigma = 10.0

[MODULE_CALIBRATION_ASSOCIATION]
masters_search_window_days = [-1, 0]

[MODULE_IMAGE_PROCESSING]
bias = true
dark = false
flat = false

[MODULE_SPECTRAL_EXTRACTION]
extraction_method = "box"