# test_kpf_masters_drp_recipe.py

"""
Regression test for the master-files recipes on a limited data set.

This test follows the new two-step approach:
1. Run kpf_masters_2D.recipe on each L0 file to generate 2D files
2. Run kpf_masters_stacks.recipe to generate master calibration files

Input data are in /data/KPF-Pipeline-TestData/kpf/L0/20250307.
There are 32 input L0 FITS files, listed as follows:

[rlaher@shrek 20250307]$ /data/user/rlaher/git/neid/src/perl/filterFITSimages.pl -p IMTYPE,EXPTIME,ELAPSED,OBJECT *fits
| Count         | Filename                  | IMTYPE      | EXPTIME     | ELAPSED     | OBJECT                 |
| i             | c                         | c           | c           | c           | c                      |
              1   KP.20250307.00021.83.fits      Flatlamp          10.0        10.019         autocal-flat-all
              2   KP.20250307.00080.37.fits      Flatlamp          10.0          10.0         autocal-flat-all
              3   KP.20250307.00138.77.fits      Flatlamp          10.0          10.0         autocal-flat-all
              4   KP.20250307.00197.08.fits      Flatlamp          10.0          10.0         autocal-flat-all
              5   KP.20250307.00255.58.fits      Flatlamp          10.0        10.016         autocal-flat-all
              6   KP.20250307.00314.18.fits      Flatlamp          10.0        10.076         autocal-flat-all
              7   KP.20250307.00372.82.fits      Flatlamp          10.0        10.051         autocal-flat-all
              8   KP.20250307.00431.41.fits      Flatlamp          10.0          10.0         autocal-flat-all
              9   KP.20250307.00489.87.fits      Flatlamp          10.0        10.015         autocal-flat-all
             10   KP.20250307.00548.19.fits      Flatlamp          10.0          10.0         autocal-flat-all
             11   KP.20250307.00606.53.fits      Flatlamp          10.0        10.061         autocal-flat-all
             12   KP.20250307.03636.94.fits          Bias           0.0         0.024             autocal-bias
             13   KP.20250307.03686.83.fits          Bias           0.0         0.019             autocal-bias
             14   KP.20250307.03736.85.fits          Bias           0.0          0.02             autocal-bias
             15   KP.20250307.03786.80.fits          Bias           0.0         0.021             autocal-bias
             16   KP.20250307.03836.71.fits          Bias           0.0           0.0             autocal-bias
             17   KP.20250307.03886.63.fits          Bias           0.0           0.0             autocal-bias
             18   KP.20250307.03936.68.fits          Bias           0.0           0.0             autocal-bias
             19   KP.20250307.04184.68.fits          Dark        1200.0        1200.0             autocal-dark
             20   KP.20250307.08950.72.fits          Dark        1200.0        1200.0             autocal-dark
             21   KP.20250307.61770.12.fits          Dark        1200.0        1200.0             autocal-dark
             22   KP.20250307.65367.06.fits          Dark        1200.0        1200.0             autocal-dark
             23   KP.20250307.67445.34.fits       Arclamp          60.0          60.0     autocal-lfc-all-morn
             24   KP.20250307.67553.80.fits       Arclamp          60.0        60.019     autocal-lfc-all-morn
             25   KP.20250307.67662.32.fits       Arclamp          60.0          60.0     autocal-lfc-all-morn
             26   KP.20250307.67770.90.fits       Arclamp          60.0         60.02     autocal-lfc-all-morn
             27   KP.20250307.67879.27.fits       Arclamp          60.0        60.018     autocal-lfc-all-morn
             28   KP.20250307.67987.67.fits       Arclamp          60.0          60.0     autocal-lfc-all-morn
             29   KP.20250307.68096.01.fits       Arclamp          60.0          60.0     autocal-lfc-all-morn
             30   KP.20250307.68204.50.fits       Arclamp          60.0         60.02     autocal-lfc-all-morn
             31   KP.20250307.68312.87.fits       Arclamp          60.0        60.103     autocal-lfc-all-morn
             32   KP.20250307.68421.37.fits       Arclamp          60.0          60.0     autocal-lfc-all-morn

NOTE: KP.20250307.05481.40.fits is also present (added later as required for order-mask generation),
but is excluded from the testing of recipes/kpf_masters_stacks.recipe

There are 4 FITS 2D master files generated by this unit test in /data/KPF-Pipeline-TestData/kpf/masters/pool.

[rlaher@shrek pool]$ /data/user/rlaher/git/neid/src/perl/filterFITSimages.pl -p IMTYPE,OBJECT *fits
| Count         | Filename                                              | IMTYPE      | OBJECT                 |
| i             | c                                                     | c           | c                      |
              1   kpf_20250307_master_arclamp_autocal-lfc-all-morn.fits       Arclamp     autocal-lfc-all-morn
              2   kpf_20250307_master_bias_autocal-bias.fits                     Bias             autocal-bias
              3   kpf_20250307_master_dark_autocal-dark.fits                     Dark             autocal-dark
              4   kpf_20250307_master_flat.fits                                  Flat         autocal-flat-all

Here is the complete list of master files generated by this test in
/data/KPF-Pipeline-TestData/kpf/masters/20250307/:

[rlaher@shrek 20250307]$ ls -ltr
total 4107000
-rw-r--r--. 1 root root 536944320 Dec 20 18:19 kpf_20250307_master_bias_autocal-bias.fits
-rw-r--r--. 1 root root 536947200 Dec 20 18:21 kpf_20250307_master_dark_autocal-dark.fits
-rw-r--r--. 1 root root 805400640 Dec 20 18:23 kpf_20250307_master_flat.fits
-rw-r--r--. 1 root root 532748160 Dec 20 18:25 kpf_20250307_master_arclamp_autocal-lfc-all-morn.fits
-rw-r--r--. 1 root root     19397 Dec 20 18:28 kpf_20250307_master_flat_GREEN_CCD.csv
-rw-r--r--. 1 root root     17901 Dec 20 18:31 kpf_20250307_master_flat_RED_CCD.csv
-rw-r--r--. 1 root root 938629440 Dec 20 18:31 kpf_20250307_master_flat_norect.fits
-rw-r--r--. 1 root root 266973120 Dec 20 18:32 kpf_20250307_order_mask.fits
-rw-r--r--. 1 root root  33056640 Dec 20 18:34 kpf_20250307_order_mask_L1.fits
-rw-r--r--. 1 root root   3594240 Dec 20 18:35 kpf_20250307_order_mask_L2.fits
-rw-r--r--. 1 root root  33039360 Dec 20 18:37 kpf_20250307_master_flat_norect_L1.fits
-rw-r--r--. 1 root root   3576960 Dec 20 18:37 kpf_20250307_master_flat_norect_L2.fits
-rw-r--r--. 1 root root  33039360 Dec 20 18:40 kpf_20250307_master_flat_L1.fits
-rw-r--r--. 1 root root   3576960 Dec 20 18:41 kpf_20250307_master_flat_L2.fits
-rw-r--r--. 1 root root  33042240 Dec 20 18:49 kpf_20250307_master_dark_autocal-dark_L1.fits
-rw-r--r--. 1 root root   3576960 Dec 20 18:50 kpf_20250307_master_dark_autocal-dark_L2.fits
-rw-r--r--. 1 root root  33039360 Dec 20 18:55 kpf_20250307_master_bias_autocal-bias_L1.fits
-rw-r--r--. 1 root root   3576960 Dec 20 18:55 kpf_20250307_master_bias_autocal-bias_L2.fits
-rw-r--r--. 1 root root  33042240 Dec 20 19:03 kpf_20250307_master_arclamp_autocal-lfc-all-morn_L1.fits
-rw-r--r--. 1 root root   3576960 Dec 20 19:03 kpf_20250307_master_arclamp_autocal-lfc-all-morn_L2.fits
-rw-r--r--. 1 root root  37092150 Dec 20 20:13 kpf_20250307_master_WLS_autocal-lfc-all-morn_RED_L1.json.gz
-rw-r--r--. 1 root root  32941629 Dec 20 21:08 kpf_20250307_master_WLS_autocal-lfc-all-morn_GREEN_L1.json.gz
-rw-r--r--. 1 root root  33042240 Dec 20 21:08 kpf_20250307_master_WLS_autocal-lfc-all-morn_L1.fits

Here is how to run only this test manually:

ssh rlaher@shrek.caltech.edu
cd /data/user/rlaher/git/KPF-Pipeline
docker rm russ_regress_test
docker run -it
           --name russ_regress_test
           -v /data/user/rlaher/git/KPF-Pipeline:/code/KPF-Pipeline
           -v /data/KPF-Pipeline-TestData/kpf/:/data
           -v /data/KPF-Pipeline-TestData/kpf/masters:/masters
           --network=host -e DBPORT=6125 -e DBNAME=kpfopsdb -e DBUSER=kpfporuss -e DBSERVER=127.0.0.1
           -e TSDBPORT=6127 -e TSDBNAME=timeseriesopsdb -e TSDBUSER=timeseriesopsuser -e TSDBSERVER=127.0.0.1 kpf-drp:latest bash

export DBPASS="?????????????"
export TSDBPASS="???????????????????"
cd /code/KPF-Pipeline/
pytest -s tests/regression/test_kpf_masters_drp_recipe.py

The -s option is to run pytest and capture stdout from the logger and print statements in the code.

The test follows a multi-step process:
1. Process all L0 files to 2D files using kpf_masters_2D.recipe (with multiprocessing)
2. Generate master calibration files using kpf_masters_stacks.recipe
3. Generate master files for order trace, order rectification, and order mask
4. Generate master L1 and L2 files
5. Generate master WLS files
"""

from kpfpipe.tools.recipe_test_unit import recipe_test
from kpfpipe.pipelines.kpf_parse_ast import RecipeError
import os
from astropy.io import fits
import numpy as np
import concurrent.futures
from glob import glob


masters_test_date = '20250307'
l0dir = '/data/L0/' + masters_test_date
l2ddir = '/data/2D/' + masters_test_date
pooldir = '/masters/pool'
procdatedir = '/masters/' + masters_test_date


# Load the new recipes
master_2d_recipe = open('recipes/kpf_masters_2D.recipe', 'r').read()
master_stacks_recipe = open('recipes/kpf_masters_stacks.recipe', 'r').read()
master_order_trace_recipe = open('recipes/create_order_trace_files.recipe', 'r').read()
master_order_rectification_recipe = open('recipes/create_order_rectification_file.recipe', 'r').read()
master_order_mask_recipe = open('recipes/create_order_mask_file.recipe', 'r').read()
master_L1_L2_recipe = open('recipes/kpf_drp.recipe', 'r').read()
master_wls_recipe = open('recipes/wls_auto.recipe', 'r').read()


# Config files
master_2d_config = 'configs/kpf_masters_drp.cfg'
master_stacks_config = 'configs/kpf_masters_drp.cfg'
master_order_trace_config = 'configs/create_order_trace_files.cfg'
master_order_rectification_config = 'configs/create_order_rectification_file.cfg'
master_order_mask_config = 'configs/create_order_mask_file.cfg'
master_L1_L2_config = 'configs/kpf_masters_l1.cfg'
master_wls_config = 'configs/wls_auto.cfg'


# Must be at module level for multiprocessing
def run_one_2d(args):
    """Run kpf_masters_2D.recipe on a single file"""
    file_path, master_2d_recipe, master_2d_config, masters_test_date = args
    recipe_test(master_2d_recipe, master_2d_config, date_dir=masters_test_date, file_path=file_path)


def computed_unclipped_statistics(input_filename,hdu_index):

    # Read in FITS image from specified HDU.

    hdul = fits.open(input_filename)
    data_array = hdul[hdu_index].data
    a = np.array(data_array)

    # Compute unclipped statistics.

    unclipped_mean = np.nanmean(a)
    unclipped_stddev = np.nanstd(a)

    print("input_filename =",input_filename)
    print("unclipped_mean =",unclipped_mean)
    print("unclipped_stddev =",unclipped_stddev)

    return unclipped_mean,unclipped_stddev


def test_master_stacks():

    """
    Generate 2D FITS files and then master stack files.
    """

    print("\n")
    print("l0dir =",l0dir)
    os.system(f'ls {l0dir}')

    # Clean up output directories
    os.system(f'rm -vrf {l2ddir}')
    os.system(f'mkdir -vp {l2ddir}')
    os.system(f'rm -vf {pooldir}/*')
    os.system(f'rm -vf {procdatedir}/*')

    # Step 1: Run kpf_masters_2D.recipe on each L0 file
    print("Step 1: Processing L0 files to 2D files...")
    fits_files = sorted(glob(os.path.join(l0dir, "*.fits")))
    print(f"Found {len(fits_files)} L0 files to process")

    # Prepare args for multiprocessing
    args = [(file_path, master_2d_recipe, master_2d_config, masters_test_date) for file_path in fits_files]

    # Run 2D processing (can use multiprocessing for speed)
    with concurrent.futures.ProcessPoolExecutor(max_workers=10) as executor:
        list(executor.map(run_one_2d, args))

    print("Step 1 complete: All L0 files processed to 2D files")

    # Exclude KP.20250307.05481.40_2D.fits by temporarily adding a ".tmp" filename extension.
    # This file is needed below for order-mask generation, but not part of the original data set for stacking.
    os.system(f'mv -f {l2ddir}/KP.20250307.05481.40_2D.fits {l2ddir}/KP.20250307.05481.40_2D.fits.tmp')

    # Step 2: Run kpf_masters_stacks.recipe to generate master files
    print("Step 2: Generating master stack calibration files...")
    recipe_test(master_stacks_recipe, master_stacks_config, date_dir=masters_test_date)
    print("Step 2 complete: Master stack files generated")

    # Re-include KP.20250307.05481.40_2D.fits by removing the ".tmp" filename extension.
    # This file is needed below for order-mask generation, but not part of the original data set for stacking.
    os.system(f'mv -f {l2ddir}/KP.20250307.05481.40_2D.fits.tmp {l2ddir}/KP.20250307.05481.40_2D.fits')


    master_bias_filename = pooldir + '/kpf_20250307_master_bias_autocal-bias.fits'
    master_dark_filename = pooldir + '/kpf_20250307_master_dark_autocal-dark.fits'
    master_flat_filename = pooldir + '/kpf_20250307_master_flat.fits'
    master_arcl_filename = pooldir + '/kpf_20250307_master_arclamp_autocal-lfc-all-morn.fits'

    # Compute statistics on GREEN_CCD image.

    hdu_index = 3        # Zero-based index.
    unclipped_mean_bias,unclipped_stddev_bias = computed_unclipped_statistics(master_bias_filename,hdu_index)
    unclipped_mean_dark,unclipped_stddev_dark = computed_unclipped_statistics(master_dark_filename,hdu_index)
    unclipped_mean_flat,unclipped_stddev_flat = computed_unclipped_statistics(master_flat_filename,hdu_index)
    unclipped_mean_arcl,unclipped_stddev_arcl = computed_unclipped_statistics(master_arcl_filename,hdu_index)

    assert np.float64(unclipped_mean_bias) > 1.8 and np.float64(unclipped_mean_bias) < 1.9
    assert np.float64(unclipped_mean_dark) > 0.002 and np.float64(unclipped_mean_dark) < 0.003
    assert np.float64(unclipped_mean_flat) > 1.073 and np.float64(unclipped_mean_flat) < 1.074
    assert np.float64(unclipped_mean_arcl) > 2080.8 and np.float64(unclipped_mean_arcl) < 2081.0


def test_master_order_trace():

    """
    Generate master order-trace files.
    """

    print("\n")

    # Input file
    master_flat_filename = 'kpf_20250307_master_flat.fits'

    # Clean up output directories and prepare inputs.  Only the master flat is required for the master order-trace recipe,
    # but the other stacked masters are copied here for use in a downstream test.
    os.system(f'rm -vrf {procdatedir}')
    os.system(f'mkdir -vp {procdatedir}')
    os.system(f'cp -pf {pooldir}/* {procdatedir}')

    # Product files to be generated
    master_order_trace_green_filename = procdatedir + '/kpf_20250307_master_flat_GREEN_CCD.csv'
    master_order_trace_red_filename = procdatedir + '/kpf_20250307_master_flat_RED_CCD.csv'

    # Run create_order_trace_files.recipe to generate master order-trace files
    print("Generating master order-trace files...")
    recipe_test(master_order_trace_recipe, master_order_trace_config, date_dir=masters_test_date)
    print("Master order-trace files generated ({master_order_trace_green_filename} and {master_order_trace_red_filename})")

    # Check if products were made
    assert os.path.isfile(master_order_trace_green_filename), f"{master_order_trace_green_filename} does not exist"
    assert os.path.isfile(master_order_trace_red_filename), f"{master_order_trace_red_filename} does not exist"


def test_master_order_rectification():

    """
    Generate master order-rectification file.
    """

    print("\n")

    # Product file to be generated
    master_order_rectification_filename = procdatedir + '/kpf_20250307_master_flat_norect.fits'

    # Run create_order_rectification_file.recipe to generate master order-rectification file
    print("Generating master order-rectification file...")
    recipe_test(master_order_rectification_recipe, master_order_rectification_config, date_dir=masters_test_date)
    print("Master order-rectification file generated ({master_order_rectification_filename})")

    # Check if product was made
    assert os.path.isfile(master_order_rectification_filename), f"{master_order_rectification_filename} does not exist"


def test_master_order_mask():

    """
    Generate master order-mask file.
    """

    print("\n")

    # Product file to be generated
    master_order_mask_filename = procdatedir + '/kpf_20250307_order_mask.fits'

    # Run create_order_mask_file.recipe to generate master order-mask file
    print("Generating master order-mask file...")
    recipe_test(master_order_mask_recipe, master_order_mask_config, date_dir=masters_test_date)
    print("Master order-mask file generated ({master_order_mask_filename})")

    # Check if product was made
    assert os.path.isfile(master_order_mask_filename), f"{master_order_mask_filename} does not exist"


def test_master_L1_L2_generation():

    """
    Generate master L1 and L2 files.
    The inputs are copied to /data/masters/20250307/ in the test_master_order_trace method above.
    """

    print("\n")

    infiles = sorted(glob(os.path.join(procdatedir, "*.fits")), reverse=True)
    infiles = [f for f in infiles if 'L1' not in f and 'L2' not in f]

    # Run recipes/kpf_drp.recipe to generate master L1 and L2 files from 2D stack files
    print("Generating master L1 and L2 files...")
    for file_path in infiles:
        recipe_test(master_L1_L2_recipe,
                    master_L1_L2_config,
                    watch=True,
                    date_dir=masters_test_date,
                    file_path=file_path)
    print("Master L1 and L2 files generated")

    master_bias_L1_filename = procdatedir + '/kpf_20250307_master_bias_autocal-bias_L1.fits'
    master_bias_L2_filename = procdatedir + '/kpf_20250307_master_bias_autocal-bias_L2.fits'
    master_dark_L1_filename = procdatedir + '/kpf_20250307_master_dark_autocal-dark_L1.fits'
    master_dark_L2_filename = procdatedir + '/kpf_20250307_master_dark_autocal-dark_L2.fits'
    master_flat_L1_filename = procdatedir + '/kpf_20250307_master_flat_L1.fits'
    master_flat_L2_filename = procdatedir + '/kpf_20250307_master_flat_L2.fits'
    master_arcl_L1_filename = procdatedir + '/kpf_20250307_master_arclamp_autocal-lfc-all-morn_L1.fits'
    master_arcl_L2_filename = procdatedir + '/kpf_20250307_master_arclamp_autocal-lfc-all-morn_L2.fits'
    master_order_mask_L1_filename = procdatedir + '/kpf_20250307_order_mask_L1.fits'
    master_order_mask_L2_filename = procdatedir + '/kpf_20250307_order_mask_L2.fits'
    master_flat_norect_L1_filename = procdatedir + '/kpf_20250307_master_flat_norect_L1.fits'
    master_flat_norect_L2_filename = procdatedir + '/kpf_20250307_master_flat_norect_L2.fits'


    # Check if products were made
    assert os.path.isfile(master_bias_L1_filename), f"{master_bias_L1_filename} does not exist"
    assert os.path.isfile(master_bias_L2_filename), f"{master_bias_L2_filename} does not exist"
    assert os.path.isfile(master_dark_L1_filename), f"{master_dark_L1_filename} does not exist"
    assert os.path.isfile(master_dark_L2_filename), f"{master_dark_L2_filename} does not exist"
    assert os.path.isfile(master_flat_L1_filename), f"{master_flat_L1_filename} does not exist"
    assert os.path.isfile(master_flat_L2_filename), f"{master_flat_L2_filename} does not exist"
    assert os.path.isfile(master_arcl_L1_filename), f"{master_arcl_L1_filename} does not exist"
    assert os.path.isfile(master_arcl_L2_filename), f"{master_arcl_L2_filename} does not exist"
    assert os.path.isfile(master_order_mask_L1_filename), f"{master_order_mask_L1_filename} does not exist"
    assert os.path.isfile(master_order_mask_L2_filename), f"{master_order_mask_L2_filename} does not exist"
    assert os.path.isfile(master_flat_norect_L1_filename), f"{master_flat_norect_L1_filename} does not exist"
    assert os.path.isfile(master_flat_norect_L2_filename), f"{master_flat_norect_L2_filename} does not exist"


def test_master_wls_generation():

    """
    Generate master WLS files.
    """

    print("\n")

    # Product files to be generated
    master_wls_filename = procdatedir + '/kpf_20250307_master_WLS_autocal-lfc-all-morn_L1.fits'
    master_wls_json_green_filename = procdatedir + '/kpf_20250307_master_WLS_autocal-lfc-all-morn_GREEN_L1.json.gz'
    master_wls_json_red_filename = procdatedir + '/kpf_20250307_master_WLS_autocal-lfc-all-morn_RED_L1.json.gz'

    # Run wls_auto.recipe to generate WLS files
    print("Generating WLS files...")
    recipe_test(master_wls_recipe, master_wls_config, date_dir=masters_test_date)
    print("WLS files generated ({master_wls_filename} and {master_wls_json_green_filename})")

    # Check if products were made
    assert os.path.isfile(master_wls_filename), f"{master_wls_filename} does not exist"
    assert os.path.isfile(master_wls_json_green_filename), f"{master_wls_json_green_filename} does not exist"
    assert os.path.isfile(master_wls_json_red_filename), f"{master_wls_json_red_filename} does not exist"


def main():
    test_master_stacks()
    # test_master_order_trace()
    # test_master_order_rectification()
    # test_master_order_mask()
    # test_master_L1_L2_generation()
    # test_master_wls_generation()


if __name__ == '__main__':
    main()
